// Derives prisma/mirror/schema.prisma from the main PostgreSQL schema, so the
// local mirror always has exactly the same tables as production.
// The mirror's engine is taken from MIRROR_DATABASE_URL in backend/.env:
//   mysql://...      -> MySQL / MariaDB
//   sqlserver://...  -> Microsoft SQL Server
// Run through `npm run mirror:setup` — do not edit the generated file by hand.
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { mirrorProvider } from './mirror-env';

const prismaDir = join(__dirname, '..', '..', 'prisma');
const source = readFileSync(join(prismaDir, 'schema.prisma'), 'utf-8');
const provider = mirrorProvider();

const generatorBlock = /generator client \{[^}]*\}/;
const datasourceBlock = /datasource db \{[^}]*\}/;
if (!generatorBlock.test(source) || !datasourceBlock.test(source)) {
  throw new Error('Could not find generator/datasource blocks in prisma/schema.prisma');
}

let mirror = source
  .replace(
    generatorBlock,
    `generator client {
  provider = "prisma-client-js"
  output   = "../../node_modules/.prisma/mirror-client"
}`,
  )
  .replace(
    datasourceBlock,
    `datasource db {
  provider = "${provider}"
  url      = env("MIRROR_DATABASE_URL")${provider === 'sqlserver' ? '\n  relationMode = "prisma"' : ''}
}`,
  );

if (provider === 'sqlserver') mirror = adaptForSqlServer(mirror);

// SQL Server differences from PostgreSQL that Prisma cannot paper over:
//  - no enum type            -> enum columns become NVARCHAR(20)
//  - multiple cascade paths / self-relations -> no DB-level foreign keys
//    (relationMode = "prisma") and NoAction on every relation
//  - IDENTITY columns reject explicit ids -> ids are plain INTs copied from production
//  - VARCHAR/TEXT are not Unicode -> NVARCHAR, so Urdu/emoji text survives
function adaptForSqlServer(schema: string): string {
  const enumNames: string[] = [];
  let out = schema.replace(/^enum (\w+) \{[^}]*\}\n*/gm, (_m, name: string) => {
    enumNames.push(name);
    return '';
  });

  if (enumNames.length) {
    const enumField = new RegExp(`^(\\s+\\w+\\s+)(${enumNames.join('|')})(\\??)(.*)$`, 'gm');
    out = out.replace(enumField, (_m, lead: string, _type: string, opt: string, rest: string) => {
      const attrs = rest.replace(/@default\((\w+)\)/, '@default("$1")');
      return `${lead}String${opt}${attrs} @db.NVarChar(20)`;
    });
  }

  return out
    .replace(/@relation\(([^)]*fields:[^)]*)\)/g, (_m, args: string) => {
      const kept = args.replace(/,\s*on(Delete|Update):\s*\w+/g, '');
      return `@relation(${kept}, onDelete: NoAction, onUpdate: NoAction)`;
    })
    .replace(/ @default\(autoincrement\(\)\)/g, '')
    .replace(/@db\.VarChar\((\d+)\)/g, '@db.NVarChar($1)')
    .replace(/@db\.Text\b/g, '@db.NVarChar(Max)');
}

const header =
  '// AUTO-GENERATED by scripts/mirror/build-mirror-schema.ts from ../schema.prisma.\n' +
  `// Local ${provider} mirror of the production PostgreSQL database. Do not edit.\n\n`;

mkdirSync(join(prismaDir, 'mirror'), { recursive: true });
const target = join(prismaDir, 'mirror', 'schema.prisma');
const existed = existsSync(target);
writeFileSync(target, header + mirror);
console.log(`${existed ? 'Updated' : 'Wrote'} prisma/mirror/schema.prisma (${provider})`);
