// Derives prisma/mirror/schema.prisma (MySQL) from the main PostgreSQL schema,
// so the local mirror always has exactly the same tables as production.
// Run through `npm run mirror:setup` — do not edit the generated file by hand.
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const prismaDir = join(__dirname, '..', '..', 'prisma');
const source = readFileSync(join(prismaDir, 'schema.prisma'), 'utf-8');

const generatorBlock = /generator client \{[^}]*\}/;
const datasourceBlock = /datasource db \{[^}]*\}/;
if (!generatorBlock.test(source) || !datasourceBlock.test(source)) {
  throw new Error('Could not find generator/datasource blocks in prisma/schema.prisma');
}

const mirror = source
  .replace(
    generatorBlock,
    `generator client {
  provider = "prisma-client-js"
  output   = "../../node_modules/.prisma/mirror-client"
}`,
  )
  .replace(
    datasourceBlock,
    `datasource db {
  provider = "mysql"
  url      = env("MIRROR_DATABASE_URL")
}`,
  );

const header =
  '// AUTO-GENERATED by scripts/mirror/build-mirror-schema.ts from ../schema.prisma.\n' +
  '// Local MySQL mirror of the production PostgreSQL database. Do not edit.\n\n';

mkdirSync(join(prismaDir, 'mirror'), { recursive: true });
writeFileSync(join(prismaDir, 'mirror', 'schema.prisma'), header + mirror);
console.log('Wrote prisma/mirror/schema.prisma');
